#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Xemarify Manager - Installer
# Tested on: Ubuntu 22.04 LTS
# Usage:
#   sudo ./install-manager.sh
#   sudo ./install-manager.sh --manager-version v1.0.1-beta --web-version v1.0.0-beta
#
# Prerequisites:
#   - docker login ghcr.io
# ============================================================

MANAGER_VERSION="${MANAGER_VERSION:-latest}"
WEB_VERSION="${WEB_VERSION:-latest}"
MANAGER_PORT="${MANAGER_PORT:-8089}"
WEB_PORT="${WEB_PORT:-3000}"
INSTALL_DIR="${INSTALL_DIR:-/opt/xemarify}"

# GHCR image paths
IMAGE_MANAGER="ghcr.io/hildanku/xemarify/manager"
IMAGE_WEB="ghcr.io/hildanku/xemarify/web"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[xemarify]${NC} $*"; }
warn() { echo -e "${YELLOW}[warning]${NC} $*"; }
err()  { echo -e "${RED}[error]${NC} $*" >&2; }

usage() {
  cat <<EOF
Usage:
  sudo ./install-manager.sh [options]

Options:
  --manager-version <tag>  Manager image tag (default: ${MANAGER_VERSION})
  --web-version <tag>      Web image tag (default: ${WEB_VERSION})
  --manager-port <port>    Manager API port (default: ${MANAGER_PORT})
  --web-port <port>        Web dashboard port (default: ${WEB_PORT})
  --install-dir <path>     Installation directory (default: ${INSTALL_DIR})
  -h, --help               Show this help

Env alternatives:
  MANAGER_VERSION, WEB_VERSION, MANAGER_PORT, WEB_PORT, INSTALL_DIR

Prerequisites:
  Run 'docker login ghcr.io' before executing this script.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --manager-version) MANAGER_VERSION="$2"; shift 2 ;;
    --web-version)     WEB_VERSION="$2"; shift 2 ;;
    --manager-port)    MANAGER_PORT="$2"; shift 2 ;;
    --web-port)        WEB_PORT="$2"; shift 2 ;;
    --install-dir)     INSTALL_DIR="$2"; shift 2 ;;
    -h|--help)         usage; exit 0 ;;
    *) err "Unknown option: $1"; usage; exit 1 ;;
  esac
done

# 1. Check root
if [[ "${EUID}" -ne 0 ]]; then
  err "Please run as root (use sudo)."
  exit 1
fi


# 2. Install Docker if not present
install_docker() {
  if command -v docker >/dev/null 2>&1; then
    log "Docker already installed: $(docker --version)"
    return
  fi

  log "Installing Docker..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg lsb-release

  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

    tee /etc/apt/sources.list.d/docker.sources <<EOF
    Types: deb
    URIs: https://download.docker.com/linux/ubuntu
    Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
    Components: stable
    Architectures: $(dpkg --print-architecture)
    Signed-By: /etc/apt/keyrings/docker.asc
    EOF

  apt-get update -qq
  apt-get install -y -qq  docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  systemctl status docker
  log "Docker installed successfully."

  groupadd docker
  usermod -aG docker $USER
  newgrp docker
}


# 3. Verify GHCR login

check_ghcr_login() {
  log "Verifying GHCR access..."
  if ! docker pull "${IMAGE_MANAGER}:${MANAGER_VERSION}" >/dev/null 2>&1; then
    err "Cannot pull ${IMAGE_MANAGER}:${MANAGER_VERSION}"
    err "Make sure you ran: docker login ghcr.io -u <username> -p <PAT>"
    exit 1
  fi
  docker pull "${IMAGE_WEB}:${WEB_VERSION}" >/dev/null 2>&1 || {
    err "Cannot pull ${IMAGE_WEB}:${WEB_VERSION}"
    exit 1
  }
  log "Images pulled: manager:${MANAGER_VERSION}, web:${WEB_VERSION}"
}


# 4. Generate secrets & env files

gen_secret() { openssl rand -base64 32 | tr -d '/+=' | head -c 48; }
gen_token()  { openssl rand -hex 24; }

generate_env() {
  mkdir -p "${INSTALL_DIR}"

  local ENV_FILE="${INSTALL_DIR}/.env"
  local MANAGER_ENV="${INSTALL_DIR}/manager.env"

  if [[ -f "${ENV_FILE}" && -f "${MANAGER_ENV}" ]]; then
    warn "Env files already exist at ${INSTALL_DIR}. Skipping generation."
    warn "Delete them manually and re-run if you want fresh secrets."
    return
  fi

  local DB_PASSWORD
  DB_PASSWORD="$(gen_secret)"
  local JWT_SECRET
  JWT_SECRET="$(gen_secret)"
  local SETUP_TOKEN
  SETUP_TOKEN="$(gen_token)"

  # Detect public IP for VITE_API_BASE_URL
  local PUBLIC_IP
  PUBLIC_IP="$(curl -s -4 ifconfig.me || echo "localhost")"

  cat > "${ENV_FILE}" <<EOF
# Auto-generated by install-manager.sh
POSTGRES_USER=xemarify
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=xemarify

MANAGER_PORT=${MANAGER_PORT}
WEB_PORT=${WEB_PORT}

MANAGER_IMAGE=${IMAGE_MANAGER}:${MANAGER_VERSION}
WEB_IMAGE=${IMAGE_WEB}:${WEB_VERSION}

VITE_API_BASE_URL=http://${PUBLIC_IP}:${MANAGER_PORT}
WEB_ORIGIN=http://${PUBLIC_IP}:${WEB_PORT}
EOF

  cat > "${MANAGER_ENV}" <<EOF
# Auto-generated by install-manager.sh
DB_HOST=db
DB_PORT=5432
DB_USERNAME=xemarify
DB_PASSWORD=${DB_PASSWORD}
DB_DATABASE=xemarify
DB_SCHEMA=public
DB_SSLMODE=disable
DB_MAX_CONNS=30
DB_MIN_CONNS=5

SERVER_HOST=0.0.0.0
PORT=8089

LOG_LEVEL=info

JWT_SECRET=${JWT_SECRET}
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=168h

MANAGER_SETUP_TOKEN=${SETUP_TOKEN}
EOF

  log "Environment files generated at ${INSTALL_DIR}/"
  echo ""
  echo "=========================================="
  echo "  PUBLIC IP:    ${PUBLIC_IP}"
  echo "  SETUP TOKEN:  ${SETUP_TOKEN}"
  echo "=========================================="
  echo "  Dashboard:    http://${PUBLIC_IP}:${WEB_PORT}"
  echo "  Manager API:  http://${PUBLIC_IP}:${MANAGER_PORT}"
  echo ""
  echo "  Open the dashboard and use the setup token"
  echo "  to create your first manager account."
  echo "=========================================="
  echo ""
}


# 5. Write docker-compose.yml

write_compose() {
  local COMPOSE_FILE="${INSTALL_DIR}/docker-compose.yml"

  cat > "${COMPOSE_FILE}" <<'COMPOSE'
name: xemarify

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - xemarify

  # Copy migrations from manager image to shared volume
  migrations-init:
    image: ${MANAGER_IMAGE}
    entrypoint: ["/bin/sh", "-c"]
    command: ["cp -a /migrations/. /shared-migrations/"]
    volumes:
      - migrations_data:/shared-migrations
    restart: "no"

  migrate:
    image: migrate/migrate:v4.18.3
    depends_on:
      db:
        condition: service_healthy
      migrations-init:
        condition: service_completed_successfully
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable",
        "up"
      ]
    volumes:
      - migrations_data:/migrations:ro
    restart: "no"
    networks:
      - xemarify

  init-partitions:
    image: postgres:16-alpine
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        for i in 0 1 2 3 4 5 6; do
          START=$$(date -d "+$${i} months" +"%Y-%m-01")
          END=$$(date -d "+$$((i+1)) months" +"%Y-%m-01")
          NAME="events_$$(date -d "+$${i} months" +"%Y_%m")"
          psql -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c \
            "CREATE TABLE IF NOT EXISTS $${NAME} PARTITION OF events FOR VALUES FROM ('$${START}') TO ('$${END}');" 2>/dev/null || true
        done
    restart: "no"
    networks:
      - xemarify

  manager:
    image: ${MANAGER_IMAGE}
    restart: unless-stopped
    env_file:
      - ./manager.env
    depends_on:
      init-partitions:
        condition: service_completed_successfully
    ports:
      - "${MANAGER_PORT}:8089"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8089/health >/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - xemarify

  web:
    image: ${WEB_IMAGE}
    restart: unless-stopped
    depends_on:
      manager:
        condition: service_healthy
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      ORIGIN: ${WEB_ORIGIN}
    ports:
      - "${WEB_PORT}:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000 >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s
    networks:
      - xemarify

volumes:
  db_data:
  migrations_data:

networks:
  xemarify:
    driver: bridge
COMPOSE

  log "docker-compose.yml written to ${INSTALL_DIR}/"
}


# 6. Start the stack

start_stack() {
  log "Starting Xemarify stack..."
  cd "${INSTALL_DIR}"
  docker compose up -d

  log "Waiting for services to be healthy..."
  local retries=0
  local max_retries=30

  while [[ $retries -lt $max_retries ]]; do
    if docker compose ps --format json | grep -q '"Health":"healthy"' 2>/dev/null || \
       docker compose ps | grep -q "(healthy)" 2>/dev/null; then

      # Check if manager specifically is healthy
      if docker compose ps manager | grep -q "healthy"; then
        log "Manager is healthy!"
        break
      fi
    fi

    retries=$((retries + 1))
    sleep 5
  done

  if [[ $retries -ge $max_retries ]]; then
    warn "Timeout waiting for services. Check logs with:"
    warn "  cd ${INSTALL_DIR} && docker compose logs"
  else
    echo ""
    log "============================================"
    log "  Xemarify Manager deployed successfully!"
    log "============================================"
    log ""
    log "  Status:  docker compose ps"
    log "  Logs:    docker compose logs -f"
    log "  Stop:    docker compose down"
    log "  Reset:   docker compose down -v"
    log ""
  fi
}


# 8. Setup firewall (optional, non-blocking)

setup_firewall() {
  if command -v ufw >/dev/null 2>&1; then
    log "Configuring UFW firewall..."
    ufw allow "${MANAGER_PORT}/tcp" >/dev/null 2>&1 || true
    ufw allow "${WEB_PORT}/tcp" >/dev/null 2>&1 || true
    log "Ports ${MANAGER_PORT} and ${WEB_PORT} opened."
  fi
}


# Main

main() {
  log "Xemarify Manager Installer"
  log "Manager: ${IMAGE_MANAGER}:${MANAGER_VERSION}"
  log "Web:     ${IMAGE_WEB}:${WEB_VERSION}"
  log "Target:  ${INSTALL_DIR}"
  echo ""

  install_docker
  check_ghcr_login
  generate_env
  write_compose
  setup_firewall
  start_stack
}

main