package engine

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

type EngineMetrics struct {
	EventsTotal         prometheus.Counter
	RulesEvaluatedTotal prometheus.Counter
	AlertsTotal         prometheus.Counter
	StateEntries        prometheus.Gauge
	ProcessingLatency   prometheus.Histogram
	StateRestoreTotal   prometheus.Counter
	StateRestoreFailed  prometheus.Counter
	StateRestoreLatency prometheus.Histogram
	DuplicateAlerts     prometheus.Counter
	DegradedMode        prometheus.Gauge
	StateStaleness      prometheus.Gauge
}

func NewEngineMetrics() *EngineMetrics {
	return &EngineMetrics{
		EventsTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_events_total",
			Help: "Total number of events processed by the detection engine.",
		}),
		RulesEvaluatedTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_rules_evaluated_total",
			Help: "Total number of rule evaluations performed by the detection engine.",
		}),
		AlertsTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_alerts_total",
			Help: "Total number of alerts generated by the detection engine.",
		}),
		StateEntries: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "xemarify_engine_state_entries",
			Help: "Current number of in-memory correlation states.",
		}),
		ProcessingLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "xemarify_engine_processing_latency_seconds",
			Help:    "Latency of processing a single event through the detection engine.",
			Buckets: prometheus.DefBuckets,
		}),
		StateRestoreTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_state_restore_total",
			Help: "Total number of runtime state restore attempts.",
		}),
		StateRestoreFailed: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_state_restore_failed_total",
			Help: "Total number of runtime state restore failures.",
		}),
		StateRestoreLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "xemarify_engine_state_restore_latency_seconds",
			Help:    "Latency of runtime state restore at startup.",
			Buckets: prometheus.DefBuckets,
		}),
		DuplicateAlerts: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_duplicate_alerts_suppressed_total",
			Help: "Total number of duplicate alerts suppressed by durable dedup key.",
		}),
		DegradedMode: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "xemarify_engine_degraded_mode",
			Help: "Detection engine degraded mode flag (1=degraded, 0=healthy).",
		}),
		StateStaleness: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "xemarify_engine_restored_state_staleness_seconds",
			Help: "Maximum staleness in seconds across restored runtime states.",
		}),
	}
}
