package engine

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

type EngineMetrics struct {
	EventsTotal         prometheus.Counter
	RulesEvaluatedTotal prometheus.Counter
	AlertsTotal         prometheus.Counter
	StateEntries        prometheus.Gauge
	ProcessingLatency   prometheus.Histogram
	StateRestoreTotal   prometheus.Counter
	StateRestoreFailed  prometheus.Counter
	StateRestoreLatency prometheus.Histogram
	DuplicateAlerts     prometheus.Counter
	DegradedMode        prometheus.Gauge
	StateStaleness      prometheus.Gauge

	AlertBufferDepth    prometheus.Gauge
	AlertFlushTotal     prometheus.Counter
	AlertFlushBatchSize prometheus.Histogram
	AlertFlushFailed    prometheus.Counter

	StateBufferDepth    prometheus.Gauge
	StateFlushTotal     prometheus.Counter
	StateFlushBatchSize prometheus.Histogram
	StateFlushFailed    prometheus.Counter

	EvalBufferDepth    prometheus.Gauge
	EvalFlushTotal     prometheus.Counter
	EvalFlushBatchSize prometheus.Histogram
	EvalFlushFailed    prometheus.Counter

	DedupBufferDepth    prometheus.Gauge
	DedupFlushTotal     prometheus.Counter
	DedupFlushBatchSize prometheus.Histogram
	DedupFlushFailed    prometheus.Counter
}

func NewEngineMetrics() *EngineMetrics {
	return &EngineMetrics{
		EventsTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_events_total",
			Help: "Total number of events processed by the detection engine.",
		}),
		RulesEvaluatedTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_rules_evaluated_total",
			Help: "Total number of rule evaluations performed by the detection engine.",
		}),
		AlertsTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_alerts_total",
			Help: "Total number of alerts generated by the detection engine.",
		}),
		StateEntries: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "xemarify_engine_state_entries",
			Help: "Current number of in-memory correlation states.",
		}),
		ProcessingLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "xemarify_engine_processing_latency_seconds",
			Help:    "Latency of processing a single event through the detection engine.",
			Buckets: prometheus.DefBuckets,
		}),
		StateRestoreTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_state_restore_total",
			Help: "Total number of runtime state restore attempts.",
		}),
		StateRestoreFailed: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_state_restore_failed_total",
			Help: "Total number of runtime state restore failures.",
		}),
		StateRestoreLatency: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "xemarify_engine_state_restore_latency_seconds",
			Help:    "Latency of runtime state restore at startup.",
			Buckets: prometheus.DefBuckets,
		}),
		DuplicateAlerts: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_duplicate_alerts_suppressed_total",
			Help: "Total number of duplicate alerts suppressed by durable dedup key.",
		}),
		DegradedMode: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "xemarify_engine_degraded_mode",
			Help: "Detection engine degraded mode flag (1=degraded, 0=healthy).",
		}),
		StateStaleness: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "xemarify_engine_restored_state_staleness_seconds",
			Help: "Maximum staleness in seconds across restored runtime states.",
		}),
		AlertBufferDepth: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "xemarify_engine_alert_buffer_depth",
			Help: "Current number of alerts buffered waiting for batch flush.",
		}),
		AlertFlushTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_alert_flush_total",
			Help: "Total number of alert batch flush operations.",
		}),
		AlertFlushBatchSize: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "xemarify_engine_alert_flush_batch_size",
			Help:    "Number of alerts in each batch flush.",
			Buckets: []float64{1, 5, 10, 25, 50, 100, 250},
		}),
		AlertFlushFailed: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_alert_flush_failed_total",
			Help: "Total number of alert batch flush operations that had partial failures.",
		}),
		StateBufferDepth: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "xemarify_engine_state_buffer_depth",
			Help: "Current number of state upserts buffered waiting for batch flush.",
		}),
		StateFlushTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_state_flush_total",
			Help: "Total number of state batch flush operations.",
		}),
		StateFlushBatchSize: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "xemarify_engine_state_flush_batch_size",
			Help:    "Number of state upserts in each batch flush.",
			Buckets: []float64{1, 5, 10, 25, 50, 100, 250},
		}),
		StateFlushFailed: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_state_flush_failed_total",
			Help: "Total number of state batch flush operations that had partial failures.",
		}),
		EvalBufferDepth: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "xemarify_engine_eval_buffer_depth",
			Help: "Current number of rule evaluations buffered waiting for batch flush.",
		}),
		EvalFlushTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_eval_flush_total",
			Help: "Total number of evaluation batch flush operations.",
		}),
		EvalFlushBatchSize: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "xemarify_engine_eval_flush_batch_size",
			Help:    "Number of evaluations in each batch flush.",
			Buckets: []float64{1, 5, 10, 25, 50, 100, 250, 500},
		}),
		EvalFlushFailed: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_eval_flush_failed_total",
			Help: "Total number of evaluation batch flush operations that had partial failures.",
		}),
		DedupBufferDepth: promauto.NewGauge(prometheus.GaugeOpts{
			Name: "xemarify_engine_dedup_buffer_depth",
			Help: "Current number of dedup entries buffered waiting for batch flush.",
		}),
		DedupFlushTotal: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_dedup_flush_total",
			Help: "Total number of dedup batch flush operations.",
		}),
		DedupFlushBatchSize: promauto.NewHistogram(prometheus.HistogramOpts{
			Name:    "xemarify_engine_dedup_flush_batch_size",
			Help:    "Number of dedup entries in each batch flush.",
			Buckets: []float64{1, 5, 10, 25, 50, 100},
		}),
		DedupFlushFailed: promauto.NewCounter(prometheus.CounterOpts{
			Name: "xemarify_engine_dedup_flush_failed_total",
			Help: "Total number of dedup batch flush operations that had partial failures.",
		}),
	}
}
