INSERT INTO rules (id, name, description, level, enabled, condition, tags, version, created_by, created_at, updated_at)
VALUES
    (
        '11111111-1111-4111-8111-111111111101',
        'SSH brute force by source IP',
        'Trigger when repeated Linux login failures are observed from the same source IP in a short window.',
        'HIGH',
        TRUE,
        $$ {"type":"threshold","event_type":"login_failed","group_by":["source_ip"],"threshold":5,"window_sec":300,"severity":"HIGH"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'syslog', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111102',
        'SSH brute force by user',
        'Trigger when the same account experiences repeated Linux login failures before a likely compromise attempt.',
        'HIGH',
        TRUE,
        $$ {"type":"threshold","event_type":"login_failed","group_by":["user"],"threshold":8,"window_sec":600,"severity":"HIGH"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'syslog', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111103',
        'Authentication failure burst on host',
        'Trigger when a host reports a broad burst of Linux login failures that may indicate distributed guessing.',
        'MEDIUM',
        TRUE,
        $$ {"type":"threshold","event_type":"login_failed","group_by":["hostname"],"threshold":20,"window_sec":600,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'syslog', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111104',
        'SSH invalid user probing',
        'Trigger when repeated invalid SSH usernames are attempted from one source IP.',
        'MEDIUM',
        TRUE,
        $$ {"type":"threshold","event_type":"ssh_invalid_user","group_by":["source_ip"],"threshold":4,"window_sec":300,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'syslog', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111105',
        'Repeated sudo failures by user',
        'Trigger when a user repeatedly fails sudo authentication, which often precedes privilege abuse.',
        'HIGH',
        TRUE,
        $$ {"type":"threshold","event_type":"sudo_failed","group_by":["user"],"threshold":5,"window_sec":600,"severity":"HIGH"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'syslog', 'privilege', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111106',
        'Repeated privilege escalation activity on host',
        'Trigger when a host reports multiple privilege escalation events inside one observation window.',
        'HIGH',
        TRUE,
        $$ {"type":"threshold","event_type":"privilege_escalation","group_by":["hostname"],"threshold":3,"window_sec":900,"severity":"HIGH"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'syslog', 'privilege', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111107',
        'Suspicious process execution burst',
        'Trigger when a host emits multiple suspicious process execution events in a short period.',
        'HIGH',
        TRUE,
        $$ {"type":"threshold","event_type":"process_exec_suspicious","group_by":["hostname"],"threshold":3,"window_sec":900,"severity":"HIGH"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'process', 'syslog', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111108',
        'File integrity change burst by asset',
        'Trigger when one asset records repeated file integrity changes that may indicate tampering.',
        'MEDIUM',
        TRUE,
        $$ {"type":"threshold","event_type":"file_integrity_changed","group_by":["asset"],"threshold":6,"window_sec":600,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'fim', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111109',
        'Service installation persistence signal',
        'Trigger when service installation events repeat on the same host, suggesting persistence attempts.',
        'HIGH',
        TRUE,
        $$ {"type":"threshold","event_type":"service_installed","group_by":["hostname"],"threshold":2,"window_sec":1800,"severity":"HIGH"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'persistence', 'syslog', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111110',
        'Port scan detections by source IP',
        'Trigger when repeated scan detections are attributed to the same source IP.',
        'MEDIUM',
        TRUE,
        $$ {"type":"threshold","event_type":"port_scan_detected","group_by":["source_ip"],"threshold":3,"window_sec":600,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'recon', 'network', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111111',
        'Login failures followed by success from same IP',
        'Trigger when a successful login quickly follows prior failures from the same source IP.',
        'HIGH',
        TRUE,
        $$ {"type":"sequence","group_by":["source_ip"],"window_sec":120,"severity":"HIGH","sequence_steps":["login_failed","login_success"]} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'syslog', 'conservative', 'sequence'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111112',
        'Login failures followed by success on same account',
        'Trigger when one account succeeds shortly after repeated failures, indicating possible credential guessing.',
        'HIGH',
        TRUE,
        $$ {"type":"sequence","group_by":["user"],"window_sec":180,"severity":"HIGH","sequence_steps":["login_failed","login_success"]} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'syslog', 'conservative', 'sequence'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111113',
        'Login success followed by sudo use',
        'Trigger when an account performs sudo soon after login, useful as a conservative escalation signal.',
        'MEDIUM',
        TRUE,
        $$ {"type":"sequence","group_by":["user"],"window_sec":600,"severity":"MEDIUM","sequence_steps":["login_success","sudo_used"]} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'privilege', 'conservative', 'sequence'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111114',
        'User creation followed by login',
        'Trigger when a newly created account quickly logs in, which is useful for spotting account misuse.',
        'HIGH',
        TRUE,
        $$ {"type":"sequence","group_by":["user"],"window_sec":1800,"severity":"HIGH","sequence_steps":["user_created","login_success"]} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'identity', 'persistence', 'conservative', 'sequence'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111115',
        'Service installation followed by start',
        'Trigger when a newly installed service is started soon after installation on the same host.',
        'HIGH',
        TRUE,
        $$ {"type":"sequence","group_by":["hostname"],"window_sec":900,"severity":"HIGH","sequence_steps":["service_installed","service_started"]} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'persistence', 'syslog', 'conservative', 'sequence'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111116',
        'Mixed authentication reconnaissance from source IP',
        'Trigger when one source IP produces a mix of failed login, invalid user, and sudo failure activity.',
        'HIGH',
        TRUE,
        $$ {"type":"correlation","group_by":["source_ip"],"window_sec":900,"severity":"HIGH","threshold":5,"correlation_event_types":["login_failed","ssh_invalid_user","sudo_failed"],"min_distinct_event_types":2} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'recon', 'conservative', 'correlation'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111117',
        'Privilege activity chain on host and user',
        'Trigger when login, sudo use, and privilege escalation activity accumulate for the same host-user pair.',
        'HIGH',
        TRUE,
        $$ {"type":"correlation","group_by":["hostname","user"],"window_sec":1200,"severity":"HIGH","threshold":4,"correlation_event_types":["login_success","sudo_used","privilege_escalation"],"min_distinct_event_types":2} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'privilege', 'conservative', 'correlation'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111118',
        'Login failure spike per host',
        'Trigger when the current login failure bucket is significantly above the historical baseline for a host.',
        'MEDIUM',
        TRUE,
        $$ {"type":"anomaly","event_type":"login_failed","group_by":["hostname"],"window_sec":300,"baseline_window_sec":3600,"spike_factor":3,"anomaly_min_count":12,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'auth', 'anomaly', 'conservative'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111119',
        'Sudo usage spike per host',
        'Trigger when sudo usage on a host sharply exceeds its normal baseline.',
        'MEDIUM',
        TRUE,
        $$ {"type":"anomaly","event_type":"sudo_used","group_by":["hostname"],"window_sec":600,"baseline_window_sec":7200,"spike_factor":2.5,"anomaly_min_count":6,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'linux', 'privilege', 'anomaly', 'conservative'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111120',
        'Web login brute force by source IP',
        'Trigger when one source IP repeatedly fails web application logins.',
        'HIGH',
        TRUE,
        $$ {"type":"threshold","event_type":"web_login_failed","group_by":["source_ip"],"threshold":10,"window_sec":300,"severity":"HIGH"} $$::jsonb,
        ARRAY['default-rule-pack', 'web', 'app', 'auth', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111121',
        'Web 401 burst by source IP',
        'Trigger when one source IP receives repeated unauthorized responses, indicating probing or password guessing.',
        'MEDIUM',
        TRUE,
        $$ {"type":"threshold","event_type":"web_401","group_by":["source_ip"],"threshold":20,"window_sec":300,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'web', 'app', 'auth', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111122',
        'Web 403 burst by source IP',
        'Trigger when one source IP repeatedly hits forbidden resources.',
        'MEDIUM',
        TRUE,
        $$ {"type":"threshold","event_type":"web_403","group_by":["source_ip"],"threshold":10,"window_sec":300,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'web', 'app', 'authz', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111123',
        'Sensitive path probing by source IP',
        'Trigger when one source IP repeatedly probes administrative or sensitive web paths.',
        'MEDIUM',
        TRUE,
        $$ {"type":"threshold","event_type":"web_probe_admin_path","group_by":["source_ip"],"threshold":15,"window_sec":600,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'web', 'app', 'recon', 'conservative', 'threshold'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111124',
        'Web login failure followed by success from same IP',
        'Trigger when a web login succeeds shortly after failures from the same source IP.',
        'HIGH',
        TRUE,
        $$ {"type":"sequence","group_by":["source_ip"],"window_sec":180,"severity":"HIGH","sequence_steps":["web_login_failed","web_login_success"]} $$::jsonb,
        ARRAY['default-rule-pack', 'web', 'app', 'auth', 'conservative', 'sequence'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111125',
        'Web reconnaissance mix from source IP',
        'Trigger when one source IP accumulates multiple kinds of suspicious web access outcomes in one window.',
        'HIGH',
        TRUE,
        $$ {"type":"correlation","group_by":["source_ip"],"window_sec":900,"severity":"HIGH","threshold":6,"correlation_event_types":["web_401","web_403","web_probe_admin_path"],"min_distinct_event_types":2} $$::jsonb,
        ARRAY['default-rule-pack', 'web', 'app', 'recon', 'conservative', 'correlation'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111126',
        'Web 401 anomaly per host',
        'Trigger when unauthorized responses on one host sharply exceed the baseline.',
        'MEDIUM',
        TRUE,
        $$ {"type":"anomaly","event_type":"web_401","group_by":["hostname"],"window_sec":300,"baseline_window_sec":3600,"spike_factor":3,"anomaly_min_count":20,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'web', 'app', 'anomaly', 'conservative'],
        1,
        NULL,
        NOW(),
        NOW()
    ),
    (
        '11111111-1111-4111-8111-111111111127',
        'Web 500 anomaly per host',
        'Trigger when one application host emits an unusual spike of internal server errors.',
        'MEDIUM',
        TRUE,
        $$ {"type":"anomaly","event_type":"web_500","group_by":["hostname"],"window_sec":300,"baseline_window_sec":3600,"spike_factor":2.5,"anomaly_min_count":10,"severity":"MEDIUM"} $$::jsonb,
        ARRAY['default-rule-pack', 'web', 'app', 'availability', 'anomaly', 'conservative'],
        1,
        NULL,
        NOW(),
        NOW()
    )
ON CONFLICT (id) DO NOTHING;